### ISSUE TITLE
Building Block: block_mv

### ISSUE THREAD

**Issue by r06942072** [NAL-i5K/CWL_Common-Workflow-Language#20]
Link:
https://github.com/NAL-i5K/CWL_Common-Workflow-Language/tree/dev/block_mv

Capture the output directory
output: Dircetory

Purpose:
Reorganize the tree structure, after applying toolkit onto the file, like gff3_QC tool

**Comment by r06942072** [comment]
CWL do all operation in /tmp, so it is not able to overwrite things on local directory.

**Comment by hsiaoyi0504** [comment]
Like I commented in #19. It seems to me this block is more for practice rather than building a pipeline.

**Comment by r06942072** [comment]
The purpose of block_mv: 
after applying tool to the data, move the output file to the corresponding place in directory tree.
(e.g.)
After executing **update_gff.py** in coordinate conversion tool, move the newly-produced *.gff file into the directory tree.

**Comment by r06942072** [comment]
I am blocked by 
- How to stock multiple type of data into InitialWorkDir ?
 class: InitialWorkDirRequirement, listing:

Thinking of a scenario, 
There are two inputs , one is File[] and the other is Directory
And I aim to move those File[] into the Directory.
After moving, return a single Directory, which include the File[] I be placed in a correct place.

Hmm... but how to write it in cwl?

**Comment by hsiaoyi0504** [comment]
My point is that I don't see any difference of this block and the actual `mv` command.
We don't mean to write a wrapper of single linux command, right ?
It seems to me that we should just use `mv` command in a workflow without creating a block for that.

**Comment by r06942072** [comment]
I think we should dress ```mv``` command up as a CWL building block.
See #21

**Comment by r06942072** [comment]
Result:
- Following two pics are a demo of moving apple into data
![block_mv1.PNG](https://images.zenhubusercontent.com/5bbf5ebe19e5685bccf0e4fc/ce063ee2-1d5b-4bf6-952b-bf3e71fefb91)
![block_mv2.PNG](https://images.zenhubusercontent.com/5bbf5ebe19e5685bccf0e4fc/39da23d3-e0a8-4bfe-a538-49bbb1c70059)

**Comment by r06942072** [comment]
https://www.biostars.org/p/242878/

**Comment by r06942072** [comment]
If I use ```cp``` command, instead of ```mv```, it works well !!
<br/>

- The result :
![image.png](https://images.zenhubusercontent.com/5bbf5ebe19e5685bccf0e4fc/e700c786-d1c6-45e4-a2e4-880fe2efc01e)

**Comment by r06942072** [comment]
[```mv``` v.s.```cp```]
**genomic.fna** is implemented by ```cp```
**.txt2** is implemented by ```mv```
This is why I choose cp instead of mv when doing folder organization.

![image](https://user-images.githubusercontent.com/32384566/54296867-0b5ea200-458c-11e9-86ba-58c6e8eab69c.png)
