### ISSUE TITLE
Building block: block_pip_install

### ISSUE THREAD

**Issue by r06942072** [NAL-i5K/CWL_Common-Workflow-Language#24]
Link:
https://github.com/NAL-i5K/CWL_Common-Workflow-Language/tree/dev/block_pip_install

**Comment by r06942072** [comment]
![pipinstall](https://user-images.githubusercontent.com/32384566/48794927-6745a800-ecc9-11e8-90e3-ae91047fbdbd.PNG)
![success_pip_install](https://user-images.githubusercontent.com/32384566/48794933-6a409880-ecc9-11e8-982f-aec2be3ac4ac.PNG)

**Comment by hsiaoyi0504** [comment]
Although installation of pip package is not like rpm packages I mentioned in #25, it seems to me that python package installation should not be included into the pipeline as well. The installation of the environment/dependencies is a one time thing per environment. However, pipeline is for things that will do many times per environment. Take a look of NCBI's pgap pipeline https://github.com/ncbi/pgap/wiki/Installation. You will see that installation of dependencies isn't a part of the pipeline job (block).

**Comment by r06942072** [comment]
not use in pipeline, see #28
