### ISSUE TITLE
Building block: block_rpm_install

### ISSUE THREAD

**Issue by r06942072** [NAL-i5K/CWL_Common-Workflow-Language#25]
Link:
https://github.com/NAL-i5K/CWL_Common-Workflow-Language/tree/dev/block_rpm_install

Install glibc 2.17 (dependency of wig2BigWig)

Install zlib 1.2.7 (dependency of wig2BigWig)

**Comment by hsiaoyi0504** [comment]
I am not pretty sure what's about, but it seems to me any installation related to rpm should not be included into any pipeline. The installation of rpm packages needs root access, but not every user of the pipeline should have that privilege.

**Comment by r06942072** [comment]
See #28
