### ISSUE TITLE
[Discussion]Divide all the work into two categories

### ISSUE THREAD

**Issue by r06942072** [NAL-i5K/CWL_Common-Workflow-Language#28]
1. Set up environment/dependencies, which run one time
2. Organism data wrangling pipeline, which run multiple times

The first one, we could achieve by genomics-VM vagrant
Link: https://github.com/NAL-i5K/genomics-VM
The second one is exactly embodied by CWL.

My thinking is when I develope CWL, I could avoid the first one
(e.g.)
pip install
rpm install
git clone the tool

**Comment by hsiaoyi0504** [comment]
Sounds good to me. :thumbsup:

**Comment by r06942072** [comment]
Yes, let's do it
