### ISSUE TITLE
Workflow: flow_setup

### ISSUE THREAD

**Issue by r06942072** [NAL-i5K/CWL_Common-Workflow-Language#54]
flow_setup is broken down into three parts: 
**setup_tree**
**download_genomic**
**download_others**

tree.cwl
wget.cwl
extract_md5checksums.cwl
check_md5sum.cwl   
gunzip.cwl

**Comment by r06942072** [comment]
Technical problem of cwl solved
- How to stack both File[] and File ?
![setup_in_gz](https://user-images.githubusercontent.com/32384566/52648427-8745cb80-2eb4-11e9-8828-e978d251a31e.PNG)

![setup_in_gz_succcesss](https://user-images.githubusercontent.com/32384566/52648542-b9efc400-2eb4-11e9-9238-ea15cd45d05e.PNG)

**Comment by r06942072** [comment]
- extract from original downloaded checksums.txt
![setup_extract_md5checksums](https://user-images.githubusercontent.com/32384566/52648826-22d73c00-2eb5-11e9-8b8b-36afefb89c21.PNG)

**Comment by r06942072** [comment]
- in outputs section of gunzip.cwl
![setup_multiplematches](https://user-images.githubusercontent.com/32384566/52657112-e52edf00-2ec5-11e9-817a-522c5ef9f1a5.PNG)

- list all the possibilities of 4 datas and do not have ambiguous
![setup_4types](https://user-images.githubusercontent.com/32384566/52657084-d47e6900-2ec5-11e9-9a07-fa874682d349.PNG)

- Success!!
![setup_success](https://user-images.githubusercontent.com/32384566/52657093-d9dbb380-2ec5-11e9-9730-524e1da446da.PNG)

**Comment by mpoelchau** [comment]
Genomic fasta (in_fasta) needs to be here at the end of the whole workflow:
data/other_species/[gggsss]/[assembly-name]/scaffold/

Genomics gff (in_gff)  needs to be here at the end of the whole workflow:
data/other_species/[gggsss]/[assembly-name]/scaffold/analyses/[annotation-release-number]/

It doesn't matter (at least to me) whether the files are in those directories at the end of flow_setup or flow_apollo2 - but it would be great if they can be moved there at the end of the entire workflow of workflows.

**Comment by r06942072** [comment]
- modify output section of gunzip.cwl, capturing all files only in one variable called **out_gunzip**. Reference in_wget (string[])
-
